export enum SettingActions {
  SET_LANGUAGE = 'SET_LANGUAGE',
  SET_SETTINGS = 'SET_SETTINGS',
}

export enum GameActions {
  SET_GAME = 'SET_GAME',
  SET_FIELD_SIZE = 'SET_FIELD_SIZE',
  SET_FIRST_WORD = 'SET_FIRST_WORD',
  SET_GAMER_TURN = 'SET_GAMER_TURN',
  ADD_WORD = 'ADD_WORD',
  ADD_POINTS = 'ADD_POINTS',
  SET_FIELD = 'SET_FIELD',
  NEXT_TURN = 'NEXT_TURN',
}

export enum AlertActions {
  SET_NOTIFY = 'SET_NOTIFY',
  REMOVE_NOTIFY = 'REMOVE_NOTIFY',
}
