export * from './about';
export * from './game';
export * from './home';
export * from './rating';
export * from './set-game';
export * from './settings';
export * from './not-found';
export * from './auth';
export * from './user';
